"""Materialise device credentials into Mosquitto broker files.

Why a script and not a broker plugin: Mosquitto cannot query PostgreSQL. The
database stays the source of truth and this tool projects it into the two files
the broker understands:

    mqtt/passwd   username:$7$<salt>$<pbkdf2-sha512>
    mqtt/acl      per-device publish permission (least privilege)

Usage (from the repository root, with the backend importable):

    python backend/scripts/sync_mqtt_credentials.py --rotate
    python backend/scripts/sync_mqtt_credentials.py --keep-existing   # demo default
    python backend/scripts/sync_mqtt_credentials.py --out-dir mqtt --print-devices

With `--keep-existing` the script derives each device password from
DEVICE_DEFAULT_PASSWORD (`<value>-<DEVICE_ID>`), which is what the seed uses —
so a demo can regenerate matching broker files without re-flashing anything.
With `--rotate` every device gets a fresh random secret, the hash is stored, and
the plaintext is written only to the generated CSV (gitignored) and the console.

Enabling auth is a deliberate, documented step: run this, then start the stack
with the auth overlay (`-f docker-compose.auth.yml`). The default compose file
keeps anonymous local access so the hackathon demo boots without ceremony.
"""
from __future__ import annotations

import argparse
import csv
import sys
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(_REPO_ROOT / "backend"))

from sqlalchemy import select  # noqa: E402

from app.config.settings import settings  # noqa: E402
from app.database.session import SessionLocal  # noqa: E402
from app.models.models import Device, Factory, Zone  # noqa: E402
from app.services import device_auth_service  # noqa: E402

GENERATED_HEADER = "# GENERATED by backend/scripts/sync_mqtt_credentials.py — do not edit by hand"


def _topic_for(device: Device, zone: Zone, factory: Factory) -> str:
    """Prefer the topic observed in telemetry; fall back to the seeded scheme."""
    return device.mqtt_topic or device_auth_service.default_topic(factory.name, zone)


def _collect(db) -> list[dict]:
    rows = db.execute(
        select(Device, Zone, Factory)
        .join(Zone, Zone.id == Device.zone_id)
        .join(Factory, Factory.id == Zone.factory_id)
        .where(Device.enabled.is_(True))
        .order_by(Device.id)
    ).all()
    return [
        {"device": device, "zone": zone, "factory": factory, "topic": _topic_for(device, zone, factory)}
        for device, zone, factory in rows
    ]


def main() -> None:
    parser = argparse.ArgumentParser(description="Sync device credentials to Mosquitto files")
    parser.add_argument("--out-dir", default="mqtt", help="directory for passwd/acl/credentials.csv")
    parser.add_argument("--rotate", action="store_true",
                        help="issue a NEW random secret for every device (default: keep existing)")
    parser.add_argument("--print-devices", action="store_true",
                        help="print the device credentials table (secrets!) to stdout")
    args = parser.parse_args()

    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    with SessionLocal() as db:
        entries = _collect(db)
        if not entries:
            print("No enabled devices found — seed the database first.")
            return

        credentials: list[tuple[str, str]] = []
        acl_entries: list[tuple[str, str | None]] = []
        rows_for_csv: list[tuple[str, str, str, str]] = []

        for entry in entries:
            device: Device = entry["device"]
            plaintext: str | None = None

            if args.rotate or device.credential is None:
                plaintext = device_auth_service.issue_credential(db, device, rotate=args.rotate)
            elif settings.device_default_password:
                # Deterministic demo path: the hash cannot be reversed, but the
                # seed uses this template, so it can be reproduced exactly.
                plaintext = f"{settings.device_default_password}-{device.device_id}"
            else:
                print(
                    f"! {device.device_id}: credential exists but its plaintext is unrecoverable "
                    f"(set DEVICE_DEFAULT_PASSWORD or run with --rotate)"
                )
                continue

            username = device.credential.username if device.credential else device.device_id
            credentials.append((username, plaintext))
            acl_entries.append((username, entry["topic"]))
            rows_for_csv.append((device.device_id, username, plaintext, entry["topic"]))
        db.commit()

    # Broker user (backend subscriber) — read all telemetry, write alerts.
    backend_user = settings.mqtt_username or "aeris-backend"
    backend_password = settings.mqtt_password
    if backend_password:
        credentials.append((backend_user, backend_password))
    else:
        print(
            "! MQTT_USERNAME/MQTT_PASSWORD not set — the backend user is missing from the "
            "password file; the backend will not authenticate against an auth-enabled broker."
        )

    passwd_path = out_dir / "passwd"
    passwd_path.write_text(
        GENERATED_HEADER + "\n" + device_auth_service.build_mosquitto_password_file(credentials),
        encoding="utf-8",
    )
    acl_path = out_dir / "acl"
    acl_path.write_text(
        GENERATED_HEADER + "\n" + device_auth_service.build_acl_file(
            acl_entries, backend_username=backend_user
        ),
        encoding="utf-8",
    )

    # Plaintext secrets for the demo/simulator ONLY. Gitignored; delete after
    # flashing a real device.
    csv_path = out_dir / "credentials.csv"
    with csv_path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.writer(handle)
        writer.writerow(["# device_id", "username", "password", "mqtt_topic"])
        for device_id, username, password, topic in rows_for_csv:
            writer.writerow([device_id, username, password, topic])

    print(f"Wrote {passwd_path} ({len(credentials)} users)")
    print(f"Wrote {acl_path} ({len(acl_entries)} device ACLs)")
    print(f"Wrote {csv_path} (plaintext — gitignored, for the simulator/flashing)")
    if args.print_devices:
        print("\ndevice_id        username         topic")
        for device_id, username, _password, topic in rows_for_csv:
            print(f"{device_id:<16} {username:<16} {topic}")


if __name__ == "__main__":
    main()
