"""Train the AERIS risk-projection regressor (default horizon: +10 minutes).

Target: the worst rule-engine risk score inside the horizon
(`future_risk_score`, generated by generate_dataset.py --task forecast).

Trains three regressors, selects by held-out MAE, and always reports the
baselines an operator should compare against:

* `no_change`  — predict today's score. If the model cannot beat this, the
  forecast adds nothing and the backend's deterministic extrapolation is the
  honest answer.
* `mean`       — predict the training mean (sanity floor).

⚠ Trained on SYNTHETIC data — pattern capability only, not site validity. The
scenarios are deterministic ramps, so a model that learns the generator's math
scores near-perfectly. Two splits are therefore reported:

* `random` — rows split at random (optimistic; adjacent ticks of one episode
  land on both sides).
* `group`  — whole episodes held out (honest generalization: no episode the
  model trained on appears in the test set).

Selection uses the group split. Treat even the group number as an upper bound:
real facilities are not deterministic scenarios.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import joblib
import numpy as np
import pandas as pd
from sklearn.ensemble import GradientBoostingRegressor, RandomForestRegressor
from sklearn.linear_model import Ridge
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.model_selection import GroupShuffleSplit, train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

_REPO_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(_REPO_ROOT))

from ml.training.generate_dataset import FEATURE_NAMES  # noqa: E402

TARGET = "future_risk_score"


def load_dataframe(path: str) -> pd.DataFrame:
    df = pd.read_csv(path)
    missing = [c for c in FEATURE_NAMES + [TARGET] if c not in df.columns]
    if missing:
        raise SystemExit(
            f"Dataset missing columns: {missing}\n"
            "Regenerate with: python ml/training/generate_dataset.py --task forecast"
        )
    return df


def build_candidates(seed: int) -> dict[str, Pipeline]:
    return {
        "ridge": Pipeline([
            ("scaler", StandardScaler()),
            ("reg", Ridge(alpha=1.0, random_state=None)),
        ]),
        # Depth/size capped deliberately: an unbounded forest on 27k rows
        # produced a 90+ MB artifact for a prototype deployment.
        "random_forest": Pipeline([
            ("reg", RandomForestRegressor(
                n_estimators=180, min_samples_leaf=4, max_depth=16,
                n_jobs=-1, random_state=seed)),
        ]),
        "gradient_boosting": Pipeline([
            ("reg", GradientBoostingRegressor(random_state=seed)),
        ]),
    }


def evaluate_regressor(pipeline: Pipeline, X_test, y_test) -> dict:
    pred = np.clip(pipeline.predict(X_test), 0.0, 100.0)
    return {
        "mae": round(float(mean_absolute_error(y_test, pred)), 3),
        "rmse": round(float(mean_squared_error(y_test, pred) ** 0.5), 3),
        "r2": round(float(r2_score(y_test, pred)), 4),
    }


def band_accuracy(pred: np.ndarray, truth: np.ndarray) -> float:
    """Fraction of projections landing in the correct risk band.

    Band accuracy is what an operator acts on ("will this escalate?"), so it is
    reported alongside MAE instead of MAE alone.
    """
    edges = [0, 30, 60, 80, 101]
    return float(np.mean(np.digitize(pred, edges) == np.digitize(truth, edges)))


def main() -> None:
    parser = argparse.ArgumentParser(description="Train the AERIS risk-projection model")
    parser.add_argument("--dataset", default="ml/datasets/aeris_forecast_synthetic.csv")
    parser.add_argument("--out", default="ml/models/aeris_forecast.joblib")
    parser.add_argument("--horizon-minutes", type=int, default=10)
    parser.add_argument("--seed", type=int, default=7)
    parser.add_argument("--version", default=None)
    args = parser.parse_args()

    df = load_dataframe(args.dataset)
    X, y = df[FEATURE_NAMES], df[TARGET]

    # --- optimistic row-wise split (reported for context only) ------------
    Xr_tr, Xr_te, yr_tr, yr_te = train_test_split(X, y, test_size=0.25, random_state=args.seed)

    # --- honest episode-level holdout (used for selection) ----------------
    groups = df["episode"] if "episode" in df.columns else df.index.to_series()
    gss = GroupShuffleSplit(n_splits=1, test_size=0.25, random_state=args.seed)
    train_idx, test_idx = next(gss.split(X, y, groups=groups))
    X_train, X_test = X.iloc[train_idx], X.iloc[test_idx]
    y_train, y_test = y.iloc[train_idx], y.iloc[test_idx]
    print(
        f"split: {len(train_idx)} train / {len(test_idx)} test rows "
        f"({groups.iloc[train_idx].nunique()} train vs {groups.iloc[test_idx].nunique()} held-out episodes)"
    )

    # Baselines first — the model must earn its place.
    no_change_mae = float(mean_absolute_error(y_test, df.loc[y_test.index, "risk_score_now"]))
    mean_mae = float(mean_absolute_error(y_test, np.full(len(y_test), y_train.mean())))
    print(f"baseline no_change  MAE={no_change_mae:.3f} (group split)")
    print(f"baseline mean       MAE={mean_mae:.3f} (group split)")

    results: dict[str, dict] = {}
    best_name, best_mae, best_pipeline = None, float("inf"), None
    for name, pipeline in build_candidates(args.seed).items():
        pipeline.fit(X_train, y_train)
        metrics = evaluate_regressor(pipeline, X_test, y_test)
        # Optimistic score kept in the report so the gap is visible.
        optimistic = evaluate_regressor(pipeline, Xr_te, yr_te)
        metrics["mae_random_split"] = optimistic["mae"]
        metrics["r2_random_split"] = optimistic["r2"]
        results[name] = metrics
        print(
            f"{name:22s} group MAE={metrics['mae']:.3f} R²={metrics['r2']:.4f} "
            f"| random MAE={metrics['mae_random_split']:.3f} R²={metrics['r2_random_split']:.4f}"
        )
        if metrics["mae"] < best_mae:
            best_name, best_mae, best_pipeline = name, metrics["mae"], pipeline

    if best_mae >= no_change_mae:
        print(
            "\n⚠ Selected model does NOT beat the no-change baseline on this dataset.\n"
            "  The backend will keep preferring trend extrapolation for equal or higher\n"
            "  projections, and the artifact records this so the API can be honest about it."
        )

    print(f"\nSelected: {best_name} (MAE {best_mae:.3f})")

    # Band accuracy on the held-out episodes: the number an operator acts on.
    pred = np.clip(best_pipeline.predict(X_test), 0.0, 100.0)
    band_acc = band_accuracy(pred, y_test.values)
    print(f"Held-out episode risk-band accuracy: {band_acc:.1%}")

    version = args.version or f"forecast-{best_name}-v{pd.Timestamp.utcnow().strftime('%Y%m%d%H%M')}"
    artifact = {
        "pipeline": best_pipeline,
        "feature_names": FEATURE_NAMES,
        "version": version,
        "horizon_minutes": args.horizon_minutes,
        "metrics": {
            "selected": best_name,
            "mae": round(best_mae, 3),
            "rmse": results[best_name]["rmse"],
            "r2": results[best_name]["r2"],
            "band_accuracy_group_split": round(band_acc, 4),
            "mae_random_split": results[best_name]["mae_random_split"],
            "evaluation": "episode-level holdout (GroupShuffleSplit)",
            "baseline_no_change_mae": round(no_change_mae, 3),
            "baseline_mean_mae": round(mean_mae, 3),
            "beats_baseline": bool(best_mae < no_change_mae),
            "candidates": {k: v["mae"] for k, v in results.items()},
            "training_rows": len(df),
            "data_source": (
                "SYNTHETIC generator (forecast task, production scoring function) — "
                "deterministic scenarios, so accuracy is an upper bound only"
            ),
        },
    }
    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    joblib.dump(artifact, out)
    print(f"Saved {out} ({version})")

    metrics_path = out.with_name(out.stem + "_metrics.json")
    metrics_path.write_text(json.dumps({**results, "baselines": {
        "no_change_mae": round(no_change_mae, 3), "mean_mae": round(mean_mae, 3)}}, indent=2))
    print(f"Metrics detail: {metrics_path}")


if __name__ == "__main__":
    main()
